-- MySQL Script generated by MySQL Workbench
-- Sat Aug 29 15:36:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bsaec_bot_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bsaec_bot_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bsaec_bot_db` DEFAULT CHARACTER SET utf8 ;
USE `bsaec_bot_db` ;

-- -----------------------------------------------------
-- Table `bsaec_bot_db`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsaec_bot_db`.`students` (
  `chat_id` INT NOT NULL,
  `firstname` VARCHAR(50) NULL,
  `surname` VARCHAR(50) NULL,
  `group` VARCHAR(8) NOT NULL COMMENT 'Описывать полностью без шифрования. Пример: 19-п, 186-б и т.д',
  `specialization` INT NOT NULL COMMENT 'Шифрование по следующим ключам:\n0 - Бухгалтерский учет, анализ и контроль\n1 - Программное обеспечение информационных технологий\n2 - Промышленное и гражданское строительство\n3 - Правоведение\n4 -Санитарно-техническое обслуживание зданий и сооружений',
  `regdate` DATETIME NULL,
  UNIQUE INDEX `chat_id_UNIQUE` (`chat_id` ASC) VISIBLE,
  PRIMARY KEY (`chat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bsaec_bot_db`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bsaec_bot_db`.`media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_id` VARCHAR(255) NULL,
  `filename` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
